"""add MCP discovery catalog and sync schedules

Revision ID: 073cc76cf70d
Revises: 503d9aafba91
Create Date: 2026-08-28 14:33:08.604568
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "073cc76cf70d"
down_revision: str | Sequence[str] | None = "503d9aafba91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_discovered_resources",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("resource_uri", sa.String(length=2048), nullable=False),
        sa.Column("resource_uri_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_cycle_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "resource_uri_hash = encode(sha256(convert_to(resource_uri, 'UTF8')), 'hex')",
            name="ck_mcp_discovered_resource_uri_hash_matches",
        ),
        sa.CheckConstraint(
            "resource_uri_hash ~ '^[0-9a-f]{64}$'", name="ck_mcp_discovered_resource_uri_hash"
        ),
        sa.CheckConstraint("size IS NULL OR size >= 0", name="ck_mcp_discovered_resource_size"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "connection_id", "source_id"],
            [
                "mcp_connections.organization_id",
                "mcp_connections.workspace_id",
                "mcp_connections.id",
                "mcp_connections.source_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "connection_id",
            "resource_uri_hash",
            name="uq_mcp_discovered_resources_identity",
        ),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
    )
    op.create_index(
        op.f("ix_mcp_discovered_resources_connection_id"),
        "mcp_discovered_resources",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_discovered_resources_last_seen_cycle_id"),
        "mcp_discovered_resources",
        ["last_seen_cycle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_discovered_resources_organization_id"),
        "mcp_discovered_resources",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_discovered_resources_source_id"),
        "mcp_discovered_resources",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_discovered_resources_workspace_id"),
        "mcp_discovered_resources",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "mcp_sync_schedules",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "interval_seconds BETWEEN 300 AND 86400", name="ck_mcp_sync_schedule_interval"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by_user_id"],
            ["users.organization_id", "users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "connection_id", "source_id"],
            [
                "mcp_connections.organization_id",
                "mcp_connections.workspace_id",
                "mcp_connections.id",
                "mcp_connections.source_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "connection_id",
            "name",
            name="uq_mcp_sync_schedules_connection_name",
        ),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "id",
            "connection_id",
            "source_id",
            name="uq_mcp_sync_schedules_resource_scope",
        ),
    )
    op.create_index(
        op.f("ix_mcp_sync_schedules_connection_id"),
        "mcp_sync_schedules",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedules_created_by_user_id"),
        "mcp_sync_schedules",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedules_next_due_at"),
        "mcp_sync_schedules",
        ["next_due_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedules_organization_id"),
        "mcp_sync_schedules",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedules_source_id"), "mcp_sync_schedules", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_mcp_sync_schedules_workspace_id"),
        "mcp_sync_schedules",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "mcp_schedule_ticks",
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "trigger IN ('interval', 'manual')", name="ck_mcp_schedule_tick_trigger"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "schedule_id", "connection_id", "source_id"],
            [
                "mcp_sync_schedules.organization_id",
                "mcp_sync_schedules.workspace_id",
                "mcp_sync_schedules.id",
                "mcp_sync_schedules.connection_id",
                "mcp_sync_schedules.source_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "sync_run_id"],
            ["mcp_sync_runs.organization_id", "mcp_sync_runs.workspace_id", "mcp_sync_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "schedule_id", "scheduled_for"),
        sa.UniqueConstraint("organization_id", "workspace_id", "sync_run_id"),
    )
    op.create_index(
        op.f("ix_mcp_schedule_ticks_connection_id"),
        "mcp_schedule_ticks",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_schedule_ticks_organization_id"),
        "mcp_schedule_ticks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_schedule_ticks_schedule_id"),
        "mcp_schedule_ticks",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_schedule_ticks_scheduled_for"),
        "mcp_schedule_ticks",
        ["scheduled_for"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_schedule_ticks_source_id"), "mcp_schedule_ticks", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_mcp_schedule_ticks_sync_run_id"),
        "mcp_schedule_ticks",
        ["sync_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_schedule_ticks_workspace_id"),
        "mcp_schedule_ticks",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "mcp_sync_schedule_resources",
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("resource_uri", sa.String(length=2048), nullable=False),
        sa.Column("resource_uri_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "resource_uri_hash = encode(sha256(convert_to(resource_uri, 'UTF8')), 'hex')",
            name="ck_mcp_schedule_resource_uri_hash_matches",
        ),
        sa.CheckConstraint(
            "resource_uri_hash ~ '^[0-9a-f]{64}$'", name="ck_mcp_schedule_resource_uri_hash"
        ),
        sa.CheckConstraint("ordinal BETWEEN 0 AND 15", name="ck_mcp_schedule_resource_ordinal"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "schedule_id", "connection_id", "source_id"],
            [
                "mcp_sync_schedules.organization_id",
                "mcp_sync_schedules.workspace_id",
                "mcp_sync_schedules.id",
                "mcp_sync_schedules.connection_id",
                "mcp_sync_schedules.source_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "schedule_id", "ordinal"),
        sa.UniqueConstraint("organization_id", "workspace_id", "schedule_id", "resource_uri_hash"),
    )
    op.create_index(
        op.f("ix_mcp_sync_schedule_resources_connection_id"),
        "mcp_sync_schedule_resources",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedule_resources_organization_id"),
        "mcp_sync_schedule_resources",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedule_resources_schedule_id"),
        "mcp_sync_schedule_resources",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedule_resources_source_id"),
        "mcp_sync_schedule_resources",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_sync_schedule_resources_workspace_id"),
        "mcp_sync_schedule_resources",
        ["workspace_id"],
        unique=False,
    )
    op.add_column(
        "mcp_connections", sa.Column("discovery_cursor", sa.String(length=2048), nullable=True)
    )
    op.add_column("mcp_connections", sa.Column("discovery_cycle_id", sa.Uuid(), nullable=True))
    op.add_column("mcp_connections", sa.Column("discovery_lease_owner", sa.Uuid(), nullable=True))
    op.add_column(
        "mcp_connections",
        sa.Column("discovery_lease_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_mcp_connections_discovery_lease_expires_at"),
        "mcp_connections",
        ["discovery_lease_expires_at"],
        unique=False,
    )
    op.create_check_constraint(
        "ck_mcp_connection_discovery_cursor_cycle",
        "mcp_connections",
        "(discovery_cursor IS NULL AND discovery_cycle_id IS NULL) OR "
        "(discovery_cursor IS NOT NULL AND discovery_cycle_id IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_mcp_connection_discovery_lease",
        "mcp_connections",
        "(discovery_lease_owner IS NULL AND discovery_lease_expires_at IS NULL) OR "
        "(discovery_lease_owner IS NOT NULL "
        "AND discovery_lease_expires_at IS NOT NULL)",
    )
    op.execute(
        """
        CREATE FUNCTION protect_mcp_discovered_resource_identity()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF (NEW.organization_id, NEW.workspace_id, NEW.id,
                NEW.connection_id, NEW.source_id, NEW.resource_uri,
                NEW.resource_uri_hash, NEW.first_seen_at)
               IS DISTINCT FROM
               (OLD.organization_id, OLD.workspace_id, OLD.id,
                OLD.connection_id, OLD.source_id, OLD.resource_uri,
                OLD.resource_uri_hash, OLD.first_seen_at) THEN
                RAISE EXCEPTION 'MCP discovered resource identity is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_mcp_discovered_resources_protect_identity
        BEFORE UPDATE ON mcp_discovered_resources
        FOR EACH ROW EXECUTE FUNCTION protect_mcp_discovered_resource_identity()
        """
    )
    op.execute(
        """
        CREATE FUNCTION protect_mcp_sync_schedule_identity()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF (NEW.organization_id, NEW.workspace_id, NEW.id,
                NEW.connection_id, NEW.source_id, NEW.created_by_user_id,
                NEW.created_at)
               IS DISTINCT FROM
               (OLD.organization_id, OLD.workspace_id, OLD.id,
                OLD.connection_id, OLD.source_id, OLD.created_by_user_id,
                OLD.created_at) THEN
                RAISE EXCEPTION 'MCP sync schedule identity is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_mcp_sync_schedules_protect_identity
        BEFORE UPDATE ON mcp_sync_schedules
        FOR EACH ROW EXECUTE FUNCTION protect_mcp_sync_schedule_identity()
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_mcp_schedule_resource_catalog()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM mcp_discovered_resources AS resource
                WHERE resource.organization_id = NEW.organization_id
                  AND resource.workspace_id = NEW.workspace_id
                  AND resource.connection_id = NEW.connection_id
                  AND resource.source_id = NEW.source_id
                  AND resource.resource_uri_hash = NEW.resource_uri_hash
                  AND resource.resource_uri = NEW.resource_uri
                  AND resource.available = true
            ) THEN
                RAISE EXCEPTION 'MCP schedule resource is unavailable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_mcp_schedule_resources_validate_catalog
        BEFORE INSERT OR UPDATE ON mcp_sync_schedule_resources
        FOR EACH ROW EXECUTE FUNCTION validate_mcp_schedule_resource_catalog()
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_mcp_schedule_tick_scope()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM mcp_sync_runs AS run
                WHERE run.organization_id = NEW.organization_id
                  AND run.workspace_id = NEW.workspace_id
                  AND run.id = NEW.sync_run_id
                  AND run.connection_id = NEW.connection_id
                  AND run.source_id = NEW.source_id
            ) THEN
                RAISE EXCEPTION 'MCP schedule tick scope mismatch'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_mcp_schedule_ticks_validate_scope
        BEFORE INSERT ON mcp_schedule_ticks
        FOR EACH ROW EXECUTE FUNCTION validate_mcp_schedule_tick_scope()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_mcp_schedule_ticks_reject_update
        BEFORE UPDATE ON mcp_schedule_ticks
        FOR EACH ROW EXECUTE FUNCTION reject_mcp_sync_history_removal()
        """
    )
    for table_name in ("mcp_sync_schedules", "mcp_schedule_ticks"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_reject_delete
            BEFORE DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION reject_mcp_sync_history_removal()
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_reject_truncate
            BEFORE TRUNCATE ON {table_name}
            FOR EACH STATEMENT EXECUTE FUNCTION reject_mcp_sync_history_removal()
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in ("mcp_sync_schedules", "mcp_schedule_ticks"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_reject_truncate ON {table_name}")
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_reject_delete ON {table_name}")
    op.execute("DROP TRIGGER IF EXISTS trg_mcp_schedule_ticks_reject_update ON mcp_schedule_ticks")
    op.execute("DROP TRIGGER IF EXISTS trg_mcp_schedule_ticks_validate_scope ON mcp_schedule_ticks")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_mcp_schedule_resources_validate_catalog "
        "ON mcp_sync_schedule_resources"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_mcp_sync_schedules_protect_identity ON mcp_sync_schedules"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_mcp_discovered_resources_protect_identity "
        "ON mcp_discovered_resources"
    )
    op.execute("DROP FUNCTION IF EXISTS validate_mcp_schedule_tick_scope()")
    op.execute("DROP FUNCTION IF EXISTS validate_mcp_schedule_resource_catalog()")
    op.execute("DROP FUNCTION IF EXISTS protect_mcp_sync_schedule_identity()")
    op.execute("DROP FUNCTION IF EXISTS protect_mcp_discovered_resource_identity()")
    op.drop_constraint("ck_mcp_connection_discovery_lease", "mcp_connections", type_="check")
    op.drop_constraint("ck_mcp_connection_discovery_cursor_cycle", "mcp_connections", type_="check")
    op.drop_index(
        op.f("ix_mcp_connections_discovery_lease_expires_at"), table_name="mcp_connections"
    )
    op.drop_column("mcp_connections", "discovery_lease_expires_at")
    op.drop_column("mcp_connections", "discovery_lease_owner")
    op.drop_column("mcp_connections", "discovery_cycle_id")
    op.drop_column("mcp_connections", "discovery_cursor")
    op.drop_index(
        op.f("ix_mcp_sync_schedule_resources_workspace_id"),
        table_name="mcp_sync_schedule_resources",
    )
    op.drop_index(
        op.f("ix_mcp_sync_schedule_resources_source_id"), table_name="mcp_sync_schedule_resources"
    )
    op.drop_index(
        op.f("ix_mcp_sync_schedule_resources_schedule_id"), table_name="mcp_sync_schedule_resources"
    )
    op.drop_index(
        op.f("ix_mcp_sync_schedule_resources_organization_id"),
        table_name="mcp_sync_schedule_resources",
    )
    op.drop_index(
        op.f("ix_mcp_sync_schedule_resources_connection_id"),
        table_name="mcp_sync_schedule_resources",
    )
    op.drop_table("mcp_sync_schedule_resources")
    op.drop_index(op.f("ix_mcp_schedule_ticks_workspace_id"), table_name="mcp_schedule_ticks")
    op.drop_index(op.f("ix_mcp_schedule_ticks_sync_run_id"), table_name="mcp_schedule_ticks")
    op.drop_index(op.f("ix_mcp_schedule_ticks_source_id"), table_name="mcp_schedule_ticks")
    op.drop_index(op.f("ix_mcp_schedule_ticks_scheduled_for"), table_name="mcp_schedule_ticks")
    op.drop_index(op.f("ix_mcp_schedule_ticks_schedule_id"), table_name="mcp_schedule_ticks")
    op.drop_index(op.f("ix_mcp_schedule_ticks_organization_id"), table_name="mcp_schedule_ticks")
    op.drop_index(op.f("ix_mcp_schedule_ticks_connection_id"), table_name="mcp_schedule_ticks")
    op.drop_table("mcp_schedule_ticks")
    op.drop_index(op.f("ix_mcp_sync_schedules_workspace_id"), table_name="mcp_sync_schedules")
    op.drop_index(op.f("ix_mcp_sync_schedules_source_id"), table_name="mcp_sync_schedules")
    op.drop_index(op.f("ix_mcp_sync_schedules_organization_id"), table_name="mcp_sync_schedules")
    op.drop_index(op.f("ix_mcp_sync_schedules_next_due_at"), table_name="mcp_sync_schedules")
    op.drop_index(op.f("ix_mcp_sync_schedules_created_by_user_id"), table_name="mcp_sync_schedules")
    op.drop_index(op.f("ix_mcp_sync_schedules_connection_id"), table_name="mcp_sync_schedules")
    op.drop_table("mcp_sync_schedules")
    op.drop_index(
        op.f("ix_mcp_discovered_resources_workspace_id"), table_name="mcp_discovered_resources"
    )
    op.drop_index(
        op.f("ix_mcp_discovered_resources_source_id"), table_name="mcp_discovered_resources"
    )
    op.drop_index(
        op.f("ix_mcp_discovered_resources_organization_id"), table_name="mcp_discovered_resources"
    )
    op.drop_index(
        op.f("ix_mcp_discovered_resources_last_seen_cycle_id"),
        table_name="mcp_discovered_resources",
    )
    op.drop_index(
        op.f("ix_mcp_discovered_resources_connection_id"), table_name="mcp_discovered_resources"
    )
    op.drop_table("mcp_discovered_resources")
    # ### end Alembic commands ###
