"""add graph canvas foundation

Revision ID: 4fe98fd9356c
Revises: a4d9232f2079
Create Date: 2026-08-12 22:52:40.619251
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = "4fe98fd9356c"
down_revision: Union[str, Sequence[str], None] = "a4d9232f2079"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canvases",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("path", sa.String(length=2048), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("workspace_id", "path"),
    )
    op.create_index(
        op.f("ix_canvases_organization_id"),
        "canvases",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_relationships_tenant_from_type",
        "relationships",
        ["organization_id", "workspace_id", "from_entity_id", "relationship_type"],
        unique=False,
    )
    op.create_index(
        "ix_relationships_tenant_to_type",
        "relationships",
        ["organization_id", "workspace_id", "to_entity_id", "relationship_type"],
        unique=False,
    )
    op.create_index(
        "ix_events_tenant_occurred_id",
        "events",
        ["organization_id", "workspace_id", sa.text("occurred_at DESC"), sa.text("id DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_canvases_workspace_id"),
        "canvases",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_events_tenant_occurred_id")
    op.execute("DROP INDEX IF EXISTS ix_relationships_tenant_to_type")
    op.execute("DROP INDEX IF EXISTS ix_relationships_tenant_from_type")
    op.drop_index(op.f("ix_canvases_workspace_id"), table_name="canvases")
    op.drop_index(op.f("ix_canvases_organization_id"), table_name="canvases")
    op.drop_table("canvases")
    # ### end Alembic commands ###
