"""add action proposals and audits

Revision ID: 545c74fcdca1
Revises: e21f4a7c9b30
Create Date: 2026-08-21 11:06:42.600919
"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = '545c74fcdca1'
down_revision: Union[str, Sequence[str], None] = 'e21f4a7c9b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_proposals',
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('connector', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(operation = 'delete_record' AND risk_level = 'elevated') OR (operation = 'update_record' AND risk_level = 'standard')", name='ck_action_proposal_operation_risk'),
    sa.CheckConstraint("connector = 'odoo'", name='ck_action_proposal_connector'),
    sa.CheckConstraint("operation IN ('update_record', 'delete_record')", name='ck_action_proposal_operation'),
    sa.CheckConstraint("risk_level IN ('standard', 'elevated')", name='ck_action_proposal_risk_level'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'executed', 'failed')", name='ck_action_proposal_status'),
    sa.ForeignKeyConstraint(['organization_id', 'approved_by_user_id'], ['users.organization_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'executed_by_user_id'], ['users.organization_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'requested_by_user_id'], ['users.organization_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_action_proposals_approved_by_user_id'), 'action_proposals', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_connector'), 'action_proposals', ['connector'], unique=False)
    op.create_index(op.f('ix_action_proposals_executed_by_user_id'), 'action_proposals', ['executed_by_user_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_operation'), 'action_proposals', ['operation'], unique=False)
    op.create_index(op.f('ix_action_proposals_organization_id'), 'action_proposals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_requested_by_user_id'), 'action_proposals', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_risk_level'), 'action_proposals', ['risk_level'], unique=False)
    op.create_index(op.f('ix_action_proposals_status'), 'action_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_action_proposals_workspace_id'), 'action_proposals', ['workspace_id'], unique=False)
    op.create_table('action_audits',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(outcome = 'succeeded' AND error_code IS NULL AND error_message IS NULL) OR (outcome = 'failed' AND error_code IS NOT NULL AND error_message IS NOT NULL)", name='ck_action_audit_state_consistency'),
    sa.CheckConstraint("event_type IN ('proposed', 'approved', 'execution_succeeded', 'execution_failed')", name='ck_action_audit_event_type'),
    sa.CheckConstraint("outcome IN ('succeeded', 'failed')", name='ck_action_audit_outcome'),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'proposal_id'], ['action_proposals.organization_id', 'action_proposals.workspace_id', 'action_proposals.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'proposal_id', 'event_type', name='uq_action_audit_proposal_event')
    )
    op.create_index(op.f('ix_action_audits_actor_user_id'), 'action_audits', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_action_audits_event_type'), 'action_audits', ['event_type'], unique=False)
    op.create_index(op.f('ix_action_audits_organization_id'), 'action_audits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_action_audits_outcome'), 'action_audits', ['outcome'], unique=False)
    op.create_index(op.f('ix_action_audits_proposal_id'), 'action_audits', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_action_audits_workspace_id'), 'action_audits', ['workspace_id'], unique=False)
    op.execute(
        """
        CREATE FUNCTION enforce_action_proposal_state()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            actor_role text;
        BEGIN
            IF TG_OP = 'INSERT' THEN
                IF NEW.status <> 'pending'
                   OR NEW.approved_by_user_id IS NOT NULL
                   OR NEW.approved_at IS NOT NULL
                   OR NEW.executed_by_user_id IS NOT NULL
                   OR NEW.executed_at IS NOT NULL THEN
                    RAISE EXCEPTION 'action proposals must start pending';
                END IF;
                SELECT role INTO actor_role
                FROM memberships
                WHERE organization_id = NEW.organization_id
                  AND workspace_id = NEW.workspace_id
                  AND user_id = NEW.requested_by_user_id;
                IF actor_role IS NULL OR actor_role NOT IN ('owner', 'admin', 'editor') THEN
                    RAISE EXCEPTION 'action proposal requester lacks write access';
                END IF;
                RETURN NEW;
            END IF;

            IF (NEW.organization_id, NEW.workspace_id, NEW.id,
                NEW.requested_by_user_id, NEW.connector, NEW.operation,
                NEW.target::jsonb, NEW.parameters::jsonb, NEW.reason,
                NEW.risk_level, NEW.created_at)
               IS DISTINCT FROM
               (OLD.organization_id, OLD.workspace_id, OLD.id,
                OLD.requested_by_user_id, OLD.connector, OLD.operation,
                OLD.target::jsonb, OLD.parameters::jsonb, OLD.reason,
                OLD.risk_level, OLD.created_at) THEN
                RAISE EXCEPTION 'action proposal authorization fields are immutable';
            END IF;

            IF OLD.status = 'pending' AND NEW.status = 'approved' THEN
                IF NEW.approved_by_user_id IS NULL OR NEW.approved_at IS NULL
                   OR NEW.executed_by_user_id IS NOT NULL OR NEW.executed_at IS NOT NULL
                   OR NEW.approved_by_user_id = NEW.requested_by_user_id THEN
                    RAISE EXCEPTION 'invalid action proposal approval';
                END IF;
                SELECT role INTO actor_role
                FROM memberships
                WHERE organization_id = NEW.organization_id
                  AND workspace_id = NEW.workspace_id
                  AND user_id = NEW.approved_by_user_id;
                IF actor_role IS NULL
                   OR (NEW.operation = 'delete_record' AND actor_role <> 'owner')
                   OR (NEW.operation = 'update_record' AND actor_role NOT IN ('owner', 'admin')) THEN
                    RAISE EXCEPTION 'action proposal approver lacks permission';
                END IF;
            ELSIF OLD.status = 'approved' AND NEW.status IN ('executed', 'failed') THEN
                IF NEW.approved_by_user_id IS DISTINCT FROM OLD.approved_by_user_id
                   OR NEW.approved_at IS DISTINCT FROM OLD.approved_at
                   OR NEW.executed_by_user_id IS NULL OR NEW.executed_at IS NULL THEN
                    RAISE EXCEPTION 'invalid action proposal execution';
                END IF;
                SELECT role INTO actor_role
                FROM memberships
                WHERE organization_id = NEW.organization_id
                  AND workspace_id = NEW.workspace_id
                  AND user_id = NEW.executed_by_user_id;
                IF actor_role IS NULL OR actor_role NOT IN ('owner', 'admin') THEN
                    RAISE EXCEPTION 'action proposal executor lacks permission';
                END IF;
            ELSE
                RAISE EXCEPTION 'invalid action proposal state transition';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER action_proposals_state_guard
        BEFORE INSERT OR UPDATE ON action_proposals
        FOR EACH ROW EXECUTE FUNCTION enforce_action_proposal_state()
        """
    )
    op.execute(
        """
        CREATE FUNCTION reject_action_history_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'action history is append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER action_proposals_no_delete
        BEFORE DELETE OR TRUNCATE ON action_proposals
        FOR EACH STATEMENT EXECUTE FUNCTION reject_action_history_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER action_audits_append_only
        BEFORE UPDATE OR DELETE OR TRUNCATE ON action_audits
        FOR EACH STATEMENT EXECUTE FUNCTION reject_action_history_mutation()
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_action_audit_insert()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            proposal action_proposals%ROWTYPE;
        BEGIN
            SELECT * INTO proposal
            FROM action_proposals
            WHERE organization_id = NEW.organization_id
              AND workspace_id = NEW.workspace_id
              AND id = NEW.proposal_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'action audit proposal not found';
            END IF;
            IF NEW.event_type = 'proposed' THEN
                IF NEW.actor_user_id <> proposal.requested_by_user_id
                   OR NEW.outcome <> 'succeeded' THEN
                    RAISE EXCEPTION 'invalid proposed action audit';
                END IF;
            ELSIF NEW.event_type = 'approved' THEN
                IF NEW.actor_user_id IS DISTINCT FROM proposal.approved_by_user_id
                   OR proposal.status = 'pending' OR NEW.outcome <> 'succeeded' THEN
                    RAISE EXCEPTION 'invalid approved action audit';
                END IF;
            ELSIF NEW.event_type = 'execution_succeeded' THEN
                IF proposal.status <> 'executed'
                   OR NEW.actor_user_id IS DISTINCT FROM proposal.executed_by_user_id
                   OR NEW.outcome <> 'succeeded' THEN
                    RAISE EXCEPTION 'invalid execution success audit';
                END IF;
            ELSIF NEW.event_type = 'execution_failed' THEN
                IF proposal.status <> 'failed'
                   OR NEW.actor_user_id IS DISTINCT FROM proposal.executed_by_user_id
                   OR NEW.outcome <> 'failed' THEN
                    RAISE EXCEPTION 'invalid execution failure audit';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER action_audits_insert_guard
        BEFORE INSERT ON action_audits
        FOR EACH ROW EXECUTE FUNCTION validate_action_audit_insert()
        """
    )
    op.execute(
        """
        CREATE FUNCTION require_action_proposal_audit()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            required_event text;
            matching_audits integer;
        BEGIN
            IF TG_OP = 'INSERT' THEN
                required_event := 'proposed';
            ELSIF NEW.status = 'approved' THEN
                required_event := 'approved';
            ELSIF NEW.status = 'executed' THEN
                required_event := 'execution_succeeded';
            ELSIF NEW.status = 'failed' THEN
                required_event := 'execution_failed';
            ELSE
                RAISE EXCEPTION 'action proposal transition has no audit contract';
            END IF;

            SELECT count(*) INTO matching_audits
            FROM action_audits
            WHERE organization_id = NEW.organization_id
              AND workspace_id = NEW.workspace_id
              AND proposal_id = NEW.id
              AND event_type = required_event;
            IF matching_audits <> 1 THEN
                RAISE EXCEPTION 'action proposal transition requires matching audit';
            END IF;
            RETURN NULL;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER action_proposals_require_audit
        AFTER INSERT OR UPDATE ON action_proposals
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION require_action_proposal_audit()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS action_proposals_require_audit ON action_proposals")
    op.execute("DROP FUNCTION IF EXISTS require_action_proposal_audit()")
    op.execute("DROP TRIGGER IF EXISTS action_audits_insert_guard ON action_audits")
    op.execute("DROP FUNCTION IF EXISTS validate_action_audit_insert()")
    op.execute("DROP TRIGGER IF EXISTS action_audits_append_only ON action_audits")
    op.execute("DROP TRIGGER IF EXISTS action_proposals_no_delete ON action_proposals")
    op.execute("DROP FUNCTION IF EXISTS reject_action_history_mutation()")
    op.execute("DROP TRIGGER IF EXISTS action_proposals_state_guard ON action_proposals")
    op.execute("DROP FUNCTION IF EXISTS enforce_action_proposal_state()")
    op.drop_index(op.f('ix_action_audits_workspace_id'), table_name='action_audits')
    op.drop_index(op.f('ix_action_audits_proposal_id'), table_name='action_audits')
    op.drop_index(op.f('ix_action_audits_outcome'), table_name='action_audits')
    op.drop_index(op.f('ix_action_audits_organization_id'), table_name='action_audits')
    op.drop_index(op.f('ix_action_audits_event_type'), table_name='action_audits')
    op.drop_index(op.f('ix_action_audits_actor_user_id'), table_name='action_audits')
    op.drop_table('action_audits')
    op.drop_index(op.f('ix_action_proposals_workspace_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_status'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_risk_level'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_requested_by_user_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_organization_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_operation'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_executed_by_user_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_connector'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_approved_by_user_id'), table_name='action_proposals')
    op.drop_table('action_proposals')
    # ### end Alembic commands ###
