"""add odoo integration audit

Revision ID: 59009aa896f9
Revises: c2ca3b9f176e
Create Date: 2026-08-13 00:16:55.006719
"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = '59009aa896f9'
down_revision: Union[str, Sequence[str], None] = 'c2ca3b9f176e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_audits',
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(outcome = 'succeeded' AND error_code IS NULL AND error_message IS NULL) OR (outcome IN ('failed', 'denied') AND error_code IS NOT NULL AND error_message IS NOT NULL)", name='ck_integration_audit_state_consistency'),
    sa.CheckConstraint("outcome IN ('succeeded', 'failed', 'denied')", name='ck_integration_audit_outcome'),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_audits_operation'), 'integration_audits', ['operation'], unique=False)
    op.create_index(op.f('ix_integration_audits_organization_id'), 'integration_audits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_integration_audits_outcome'), 'integration_audits', ['outcome'], unique=False)
    op.create_index(op.f('ix_integration_audits_provider'), 'integration_audits', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_audits_tool_name'), 'integration_audits', ['tool_name'], unique=False)
    op.create_index(op.f('ix_integration_audits_workspace_id'), 'integration_audits', ['workspace_id'], unique=False)
    op.execute(
        """
        CREATE FUNCTION reject_integration_audit_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'integration_audits are append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER integration_audits_append_only
        BEFORE UPDATE OR DELETE ON integration_audits
        FOR EACH ROW EXECUTE FUNCTION reject_integration_audit_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS integration_audits_append_only ON integration_audits")
    op.execute("DROP FUNCTION IF EXISTS reject_integration_audit_mutation()")
    op.drop_index(op.f('ix_integration_audits_workspace_id'), table_name='integration_audits')
    op.drop_index(op.f('ix_integration_audits_tool_name'), table_name='integration_audits')
    op.drop_index(op.f('ix_integration_audits_provider'), table_name='integration_audits')
    op.drop_index(op.f('ix_integration_audits_outcome'), table_name='integration_audits')
    op.drop_index(op.f('ix_integration_audits_organization_id'), table_name='integration_audits')
    op.drop_index(op.f('ix_integration_audits_operation'), table_name='integration_audits')
    op.drop_table('integration_audits')
    # ### end Alembic commands ###
