"""add knowledge engine foundation

Revision ID: a4d9232f2079
Revises: b0fe58d4f237
Create Date: 2026-08-12 21:44:55.302429
"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4d9232f2079'
down_revision: Union[str, Sequence[str], None] = 'b0fe58d4f237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('frontmatter', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'document_id'], ['documents.organization_id', 'documents.workspace_id', 'documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'document_id', 'id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'document_id', 'version_number'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_organization_id'), 'document_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_versions_workspace_id'), 'document_versions', ['workspace_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunk_index_nonnegative'),
    sa.CheckConstraint('start_offset >= 0 AND end_offset > start_offset', name='ck_document_chunk_offsets'),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'document_id', 'version_id'], ['document_versions.organization_id', 'document_versions.workspace_id', 'document_versions.document_id', 'document_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'version_id', 'chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_version_id'), 'document_chunks', ['version_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_workspace_id'), 'document_chunks', ['workspace_id'], unique=False)
    op.create_table('document_links',
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('target_document_id', sa.Uuid(), nullable=True),
    sa.Column('raw_target', sa.String(length=500), nullable=False),
    sa.Column('normalized_target', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'source_document_id', 'source_version_id'], ['document_versions.organization_id', 'document_versions.workspace_id', 'document_versions.document_id', 'document_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'source_document_id'], ['documents.organization_id', 'documents.workspace_id', 'documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'target_document_id'], ['documents.organization_id', 'documents.workspace_id', 'documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'source_version_id', 'normalized_target')
    )
    op.create_index(op.f('ix_document_links_normalized_target'), 'document_links', ['normalized_target'], unique=False)
    op.create_index(op.f('ix_document_links_organization_id'), 'document_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_links_source_document_id'), 'document_links', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_links_source_version_id'), 'document_links', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_document_links_target_document_id'), 'document_links', ['target_document_id'], unique=False)
    op.create_index(op.f('ix_document_links_workspace_id'), 'document_links', ['workspace_id'], unique=False)
    op.execute(
        """
        CREATE FUNCTION reject_document_version_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'document_versions are append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER document_versions_append_only
        BEFORE UPDATE OR DELETE ON document_versions
        FOR EACH ROW EXECUTE FUNCTION reject_document_version_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS document_versions_append_only ON document_versions")
    op.execute("DROP FUNCTION IF EXISTS reject_document_version_mutation()")
    op.drop_index(op.f('ix_document_links_workspace_id'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_target_document_id'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_source_version_id'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_source_document_id'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_organization_id'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_normalized_target'), table_name='document_links')
    op.drop_table('document_links')
    op.drop_index(op.f('ix_document_chunks_workspace_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_version_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_document_versions_workspace_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_organization_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    # ### end Alembic commands ###
