"""add entity resolution foundation

Revision ID: a73340202820
Revises: 7450833f18d3
Create Date: 2026-08-13 14:57:16.882948
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "a73340202820"
down_revision: Union[str, Sequence[str], None] = "7450833f18d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM relationships
                WHERE from_entity_id = to_entity_id
            ) THEN
                RAISE EXCEPTION
                    'Phase 7 upgrade blocked: remove or remediate relationship self-loops';
            END IF;
            IF EXISTS (
                SELECT 1
                FROM relationships
                GROUP BY organization_id, workspace_id, from_entity_id,
                         to_entity_id, relationship_type
                HAVING count(*) > 1
            ) THEN
                RAISE EXCEPTION
                    'Phase 7 upgrade blocked: reconcile duplicate typed relationships';
            END IF;
        END;
        $$
        """
    )
    op.create_check_constraint(
        "ck_relationship_no_self_loop",
        "relationships",
        "from_entity_id <> to_entity_id",
    )
    op.create_unique_constraint(
        "uq_relationship_typed_edge",
        "relationships",
        [
            "organization_id",
            "workspace_id",
            "from_entity_id",
            "to_entity_id",
            "relationship_type",
        ],
    )
    op.execute(
        """
        CREATE FUNCTION require_active_entity_owner()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            field_name text;
            owner_id uuid;
            owner_ids uuid[] := ARRAY[]::uuid[];
            owner_status text;
            owner_fields_changed boolean := false;
        BEGIN
            IF TG_OP = 'UPDATE'
               AND OLD.organization_id IS NOT DISTINCT FROM NEW.organization_id
               AND OLD.workspace_id IS NOT DISTINCT FROM NEW.workspace_id THEN
                FOREACH field_name IN ARRAY TG_ARGV LOOP
                    IF (to_jsonb(OLD) ->> field_name)
                       IS DISTINCT FROM (to_jsonb(NEW) ->> field_name) THEN
                        owner_fields_changed := true;
                        EXIT;
                    END IF;
                END LOOP;
                IF NOT owner_fields_changed THEN
                    RETURN NEW;
                END IF;
            END IF;
            FOREACH field_name IN ARRAY TG_ARGV LOOP
                owner_id := NULLIF(to_jsonb(NEW) ->> field_name, '')::uuid;
                IF owner_id IS NOT NULL THEN
                    owner_ids := array_append(owner_ids, owner_id);
                END IF;
            END LOOP;
            FOR owner_id IN
                SELECT DISTINCT candidate_id
                FROM unnest(owner_ids) AS candidate_id
                ORDER BY candidate_id
            LOOP
                owner_status := NULL;
                SELECT entity.lifecycle_status
                INTO owner_status
                FROM entities entity
                WHERE entity.organization_id = NEW.organization_id
                  AND entity.workspace_id = NEW.workspace_id
                  AND entity.id = owner_id
                FOR UPDATE;
                IF owner_status IS DISTINCT FROM 'active' THEN
                    RAISE EXCEPTION 'entity owner must reference an active entity';
                END IF;
            END LOOP;
            RETURN NEW;
        END;
        $$
        """
    )
    for table_name, entity_fields in (
        ("external_references", ("entity_id",)),
        ("relationships", ("from_entity_id", "to_entity_id")),
        ("events", ("subject_entity_id",)),
        ("memories", ("subject_entity_id",)),
        ("evidence_links", ("entity_id",)),
    ):
        arguments = ", ".join(f"'{field}'" for field in entity_fields)
        op.execute(
            f"""
            CREATE TRIGGER {table_name}_active_entity_owner
            BEFORE INSERT OR UPDATE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION require_active_entity_owner({arguments})
            """
        )
    op.create_table(
        "entity_merges",
        sa.Column("source_entity_id", sa.Uuid(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column("merged_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("split_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(status = 'active' AND split_by_user_id IS NULL) OR (status = 'split' AND split_by_user_id IS NOT NULL)",
            name="ck_entity_merge_state",
        ),
        sa.CheckConstraint(
            "source_entity_id <> target_entity_id", name="ck_entity_merge_distinct_entities"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "merged_by_user_id"],
            ["users.organization_id", "users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "split_by_user_id"],
            ["users.organization_id", "users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "source_entity_id"],
            ["entities.organization_id", "entities.workspace_id", "entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "target_entity_id"],
            ["entities.organization_id", "entities.workspace_id", "entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
    )
    op.create_index(
        op.f("ix_entity_merges_organization_id"), "entity_merges", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_merges_source_entity_id"),
        "entity_merges",
        ["source_entity_id"],
        unique=False,
    )
    op.create_index(op.f("ix_entity_merges_status"), "entity_merges", ["status"], unique=False)
    op.create_index(
        op.f("ix_entity_merges_target_entity_id"),
        "entity_merges",
        ["target_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_merges_workspace_id"), "entity_merges", ["workspace_id"], unique=False
    )
    op.execute(
        """
        CREATE FUNCTION enforce_single_active_entity_merge()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            first_entity uuid;
            second_entity uuid;
        BEGIN
            IF NEW.status <> 'active' THEN
                RETURN NEW;
            END IF;
            first_entity := LEAST(NEW.source_entity_id, NEW.target_entity_id);
            second_entity := GREATEST(NEW.source_entity_id, NEW.target_entity_id);
            PERFORM pg_advisory_xact_lock(hashtextextended(first_entity::text, 0));
            PERFORM pg_advisory_xact_lock(hashtextextended(second_entity::text, 0));
            IF EXISTS (
                SELECT 1
                FROM entity_merges existing
                WHERE existing.organization_id = NEW.organization_id
                  AND existing.workspace_id = NEW.workspace_id
                  AND existing.status = 'active'
                  AND existing.id <> NEW.id
                  AND (
                      existing.source_entity_id IN (
                          NEW.source_entity_id, NEW.target_entity_id
                      )
                      OR existing.target_entity_id IN (
                          NEW.source_entity_id, NEW.target_entity_id
                      )
                  )
            ) THEN
                RAISE EXCEPTION 'entity already participates in an active merge';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER entity_merges_single_active_participation
        BEFORE INSERT OR UPDATE OF source_entity_id, target_entity_id, status
        ON entity_merges
        FOR EACH ROW EXECUTE FUNCTION enforce_single_active_entity_merge()
        """
    )
    op.execute(
        """
        CREATE FUNCTION protect_entity_merge_journal()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'entity merge journals cannot be deleted';
            END IF;
            IF OLD.organization_id IS DISTINCT FROM NEW.organization_id
               OR OLD.workspace_id IS DISTINCT FROM NEW.workspace_id
               OR OLD.source_entity_id IS DISTINCT FROM NEW.source_entity_id
               OR OLD.target_entity_id IS DISTINCT FROM NEW.target_entity_id
               OR OLD.merged_by_user_id IS DISTINCT FROM NEW.merged_by_user_id
               OR OLD.snapshot::jsonb IS DISTINCT FROM NEW.snapshot::jsonb THEN
                RAISE EXCEPTION 'entity merge journal is immutable';
            END IF;
            IF (OLD.status, OLD.split_by_user_id)
                   IS DISTINCT FROM (NEW.status, NEW.split_by_user_id)
               AND NOT (
                   OLD.status = 'active'
                   AND OLD.split_by_user_id IS NULL
                   AND NEW.status = 'split'
                   AND NEW.split_by_user_id IS NOT NULL
               ) THEN
                RAISE EXCEPTION 'invalid entity merge journal transition';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER entity_merges_protect_journal
        BEFORE UPDATE OR DELETE ON entity_merges
        FOR EACH ROW EXECUTE FUNCTION protect_entity_merge_journal()
        """
    )
    op.create_table(
        "entity_resolution_cases",
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            postgresql.ENUM(
                "organization",
                "person",
                "employee",
                "customer",
                "supplier",
                "product",
                "order",
                "invoice",
                "opportunity",
                "project",
                "ticket",
                "meeting",
                "email",
                "document",
                "decision",
                "event",
                "task",
                name="entitytype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("query_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("identifiers", sa.JSON(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("selected_entity_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_action", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(status = 'pending' AND selected_entity_id IS NULL AND resolution_action IS NULL) OR (status = 'resolved' AND selected_entity_id IS NOT NULL AND resolution_action IN ('match', 'merge')) OR (status = 'dismissed' AND selected_entity_id IS NULL AND resolution_action = 'dismiss')",
            name="ck_entity_resolution_case_state",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'resolved', 'dismissed')",
            name="ck_entity_resolution_case_status",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "requested_by_user_id"],
            ["users.organization_id", "users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "selected_entity_id"],
            ["entities.organization_id", "entities.workspace_id", "entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
    )
    op.create_index(
        op.f("ix_entity_resolution_cases_entity_type"),
        "entity_resolution_cases",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_resolution_cases_normalized_name"),
        "entity_resolution_cases",
        ["normalized_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_resolution_cases_organization_id"),
        "entity_resolution_cases",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_resolution_cases_status"),
        "entity_resolution_cases",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_resolution_cases_workspace_id"),
        "entity_resolution_cases",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "entity_resolution_audits",
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("merge_id", sa.Uuid(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IN ('match', 'dismiss', 'merge', 'split')",
            name="ck_entity_resolution_audit_action",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actor_user_id"],
            ["users.organization_id", "users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "merge_id"],
            ["entity_merges.organization_id", "entity_merges.workspace_id", "entity_merges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_resolution_audits_action"),
        "entity_resolution_audits",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_resolution_audits_merge_id"),
        "entity_resolution_audits",
        ["merge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_resolution_audits_organization_id"),
        "entity_resolution_audits",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_resolution_audits_workspace_id"),
        "entity_resolution_audits",
        ["workspace_id"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION reject_entity_resolution_audit_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'entity_resolution_audits are append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER entity_resolution_audits_append_only
        BEFORE UPDATE OR DELETE ON entity_resolution_audits
        FOR EACH ROW EXECUTE FUNCTION reject_entity_resolution_audit_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (
        "external_references",
        "relationships",
        "events",
        "memories",
        "evidence_links",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_active_entity_owner ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS require_active_entity_owner()")
    op.execute(
        "DROP TRIGGER IF EXISTS entity_resolution_audits_append_only ON entity_resolution_audits"
    )
    op.execute("DROP FUNCTION IF EXISTS reject_entity_resolution_audit_mutation()")
    op.drop_index(
        op.f("ix_entity_resolution_audits_workspace_id"), table_name="entity_resolution_audits"
    )
    op.drop_index(
        op.f("ix_entity_resolution_audits_organization_id"), table_name="entity_resolution_audits"
    )
    op.drop_index(
        op.f("ix_entity_resolution_audits_merge_id"), table_name="entity_resolution_audits"
    )
    op.drop_index(op.f("ix_entity_resolution_audits_action"), table_name="entity_resolution_audits")
    op.drop_table("entity_resolution_audits")
    op.drop_index(
        op.f("ix_entity_resolution_cases_workspace_id"), table_name="entity_resolution_cases"
    )
    op.drop_index(op.f("ix_entity_resolution_cases_status"), table_name="entity_resolution_cases")
    op.drop_index(
        op.f("ix_entity_resolution_cases_organization_id"), table_name="entity_resolution_cases"
    )
    op.drop_index(
        op.f("ix_entity_resolution_cases_normalized_name"), table_name="entity_resolution_cases"
    )
    op.drop_index(
        op.f("ix_entity_resolution_cases_entity_type"), table_name="entity_resolution_cases"
    )
    op.drop_table("entity_resolution_cases")
    op.execute("DROP TRIGGER IF EXISTS entity_merges_protect_journal ON entity_merges")
    op.execute("DROP FUNCTION IF EXISTS protect_entity_merge_journal()")
    op.execute("DROP TRIGGER IF EXISTS entity_merges_single_active_participation ON entity_merges")
    op.execute("DROP FUNCTION IF EXISTS enforce_single_active_entity_merge()")
    op.drop_index(op.f("ix_entity_merges_workspace_id"), table_name="entity_merges")
    op.drop_index(op.f("ix_entity_merges_target_entity_id"), table_name="entity_merges")
    op.drop_index(op.f("ix_entity_merges_status"), table_name="entity_merges")
    op.drop_index(op.f("ix_entity_merges_source_entity_id"), table_name="entity_merges")
    op.drop_index(op.f("ix_entity_merges_organization_id"), table_name="entity_merges")
    op.drop_table("entity_merges")
    op.execute("ALTER TABLE relationships DROP CONSTRAINT IF EXISTS uq_relationship_typed_edge")
    op.execute("ALTER TABLE relationships DROP CONSTRAINT IF EXISTS ck_relationship_no_self_loop")
    # ### end Alembic commands ###
