"""create phase one core domain

Revision ID: b0fe58d4f237
Revises:
Create Date: 2026-08-12 18:54:12.825688
"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0fe58d4f237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('api_token_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token_hash'),
    sa.UniqueConstraint('organization_id', 'email'),
    sa.UniqueConstraint('organization_id', 'id')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id'),
    sa.UniqueConstraint('organization_id', 'slug')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'path')
    )
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('entities',
    sa.Column('entity_type', sa.Enum('organization', 'person', 'employee', 'customer', 'supplier', 'product', 'order', 'invoice', 'opportunity', 'project', 'ticket', 'meeting', 'email', 'document', 'decision', 'event', 'task', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_normalized_name'), 'entities', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_entities_organization_id'), 'entities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entities_workspace_id'), 'entities', ['workspace_id'], unique=False)
    op.create_table('memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['users.organization_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('sources',
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_sources_organization_id'), 'sources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_sources_workspace_id'), 'sources', ['workspace_id'], unique=False)
    op.create_table('events',
    sa.Column('subject_entity_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'subject_entity_id'], ['entities.organization_id', 'entities.workspace_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_events_workspace_id'), 'events', ['workspace_id'], unique=False)
    op.create_table('evidence',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('pointer', sa.JSON(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'source_id'], ['sources.organization_id', 'sources.workspace_id', 'sources.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_index(op.f('ix_evidence_workspace_id'), 'evidence', ['workspace_id'], unique=False)
    op.create_table('external_references',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_model', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('raw_ref', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'entity_id'], ['entities.organization_id', 'entities.workspace_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'source_model', 'external_id')
    )
    op.create_index(op.f('ix_external_references_entity_id'), 'external_references', ['entity_id'], unique=False)
    op.create_index(op.f('ix_external_references_organization_id'), 'external_references', ['organization_id'], unique=False)
    op.create_index(op.f('ix_external_references_workspace_id'), 'external_references', ['workspace_id'], unique=False)
    op.create_table('memories',
    sa.Column('subject_entity_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.Enum('semantic', 'episodic', 'decision', 'conversation', 'business', name='memorytype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('structured_facts', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'subject_entity_id'], ['entities.organization_id', 'entities.workspace_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_memories_memory_type'), 'memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memories_organization_id'), 'memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memories_workspace_id'), 'memories', ['workspace_id'], unique=False)
    op.create_table('relationships',
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'from_entity_id'], ['entities.organization_id', 'entities.workspace_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'to_entity_id'], ['entities.organization_id', 'entities.workspace_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'id')
    )
    op.create_index(op.f('ix_relationships_from_entity_id'), 'relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_organization_id'), 'relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_relationships_relationship_type'), 'relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_to_entity_id'), 'relationships', ['to_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_workspace_id'), 'relationships', ['workspace_id'], unique=False)
    op.create_table('evidence_links',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('memory_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('(CASE WHEN entity_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN relationship_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN event_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN document_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN memory_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_evidence_link_exactly_one_target'),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'document_id'], ['documents.organization_id', 'documents.workspace_id', 'documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'entity_id'], ['entities.organization_id', 'entities.workspace_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'event_id'], ['events.organization_id', 'events.workspace_id', 'events.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'evidence_id'], ['evidence.organization_id', 'evidence.workspace_id', 'evidence.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'memory_id'], ['memories.organization_id', 'memories.workspace_id', 'memories.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id', 'relationship_id'], ['relationships.organization_id', 'relationships.workspace_id', 'relationships.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'workspace_id'], ['workspaces.organization_id', 'workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_links_document_id'), 'evidence_links', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_entity_id'), 'evidence_links', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_event_id'), 'evidence_links', ['event_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_evidence_id'), 'evidence_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_memory_id'), 'evidence_links', ['memory_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_organization_id'), 'evidence_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_relationship_id'), 'evidence_links', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_workspace_id'), 'evidence_links', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_links_workspace_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_relationship_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_organization_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_memory_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_evidence_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_event_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_entity_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_document_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_relationships_workspace_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_to_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relationship_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_organization_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_entity_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_memories_workspace_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_organization_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_memory_type'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_external_references_workspace_id'), table_name='external_references')
    op.drop_index(op.f('ix_external_references_organization_id'), table_name='external_references')
    op.drop_index(op.f('ix_external_references_entity_id'), table_name='external_references')
    op.drop_table('external_references')
    op.drop_index(op.f('ix_evidence_workspace_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_events_workspace_id'), table_name='events')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sources_workspace_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_organization_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_entities_workspace_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_organization_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_normalized_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.execute("DROP TYPE IF EXISTS memorytype")
    op.execute("DROP TYPE IF EXISTS entitytype")
    # ### end Alembic commands ###
