"""add data ingestion foundation

Revision ID: c2ca3b9f176e
Revises: 4fe98fd9356c
Create Date: 2026-08-12 23:31:44.415227
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = "c2ca3b9f176e"
down_revision: Union[str, Sequence[str], None] = "4fe98fd9356c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("parser_metadata", sa.JSON(), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('succeeded', 'failed')", name="ck_ingestion_run_status"),
        sa.CheckConstraint("byte_size >= 0", name="ck_ingestion_run_byte_size"),
        sa.CheckConstraint("candidate_count >= 0", name="ck_ingestion_run_candidate_count"),
        sa.CheckConstraint(
            "(status = 'succeeded' AND extracted_text IS NOT NULL "
            "AND error_code IS NULL AND error_message IS NULL) OR "
            "(status = 'failed' AND extracted_text IS NULL "
            "AND error_code IS NOT NULL AND error_message IS NOT NULL "
            "AND candidate_count = 0)",
            name="ck_ingestion_run_state_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "source_id"],
            ["sources.organization_id", "sources.workspace_id", "sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "source_id", "id"),
    )
    op.create_index(
        op.f("ix_ingestion_runs_organization_id"),
        "ingestion_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_runs_source_id"), "ingestion_runs", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_ingestion_runs_status"), "ingestion_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_ingestion_runs_workspace_id"), "ingestion_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "extraction_candidates",
        sa.Column("ingestion_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_index", sa.Integer(), nullable=False),
        sa.Column("candidate_type", sa.String(length=100), nullable=False),
        sa.Column("locator", sa.JSON(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')", name="ck_extraction_candidate_status"
        ),
        sa.CheckConstraint(
            "candidate_index >= 0", name="ck_extraction_candidate_index_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "source_id", "ingestion_run_id"],
            [
                "ingestion_runs.organization_id",
                "ingestion_runs.workspace_id",
                "ingestion_runs.source_id",
                "ingestion_runs.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "ingestion_run_id", "candidate_index"
        ),
    )
    op.create_index(
        op.f("ix_extraction_candidates_candidate_type"),
        "extraction_candidates",
        ["candidate_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_candidates_ingestion_run_id"),
        "extraction_candidates",
        ["ingestion_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_candidates_organization_id"),
        "extraction_candidates",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_candidates_source_id"),
        "extraction_candidates",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_candidates_status"), "extraction_candidates", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_extraction_candidates_workspace_id"),
        "extraction_candidates",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extraction_candidates_workspace_id"), table_name="extraction_candidates")
    op.drop_index(op.f("ix_extraction_candidates_status"), table_name="extraction_candidates")
    op.drop_index(op.f("ix_extraction_candidates_source_id"), table_name="extraction_candidates")
    op.drop_index(
        op.f("ix_extraction_candidates_organization_id"), table_name="extraction_candidates"
    )
    op.drop_index(
        op.f("ix_extraction_candidates_ingestion_run_id"), table_name="extraction_candidates"
    )
    op.drop_index(
        op.f("ix_extraction_candidates_candidate_type"), table_name="extraction_candidates"
    )
    op.drop_table("extraction_candidates")
    op.drop_index(op.f("ix_ingestion_runs_workspace_id"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_status"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_source_id"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_organization_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
